Sandstorm:
  NeosH5P:
    h5pPublicFolder:
      # URL of the h5p public folder. Can be absolute or relative to the base Uri.
      url: &h5pPublicFolderUrl '/_Resources/Static/H5P/'
      # File path of the h5p public folder.
      path: &h5pPublicFolderPath '%FLOW_PATH_WEB%/_Resources/Static/H5P/'
      subfolders:
        # subfolder for content. Must be named "content" for now, because H5P expects this.
        content: &h5pContentSubfolderName 'content'
        # subfolder for libraries. Must be named "libraries" for now, because H5P expects this.
        libraries: &h5pLibrarySubfolderName 'libraries'
        # Directory where the H5P core assets (from 3rd party package) are published to.
        core: &h5pCoreSubfolderName 'h5p-core'
        # Directory where the H5P editor assets (from 3rd party package) are published to.
        editor: &h5pEditorSubfolderName 'h5p-editor'
        # Directory where temporary editor files are put.
        editorTempfiles: &h5pEditorTempfilesSubfolderName 'editor-temp'
    # These can be generated as ConfigSettings by the flow command
    # ./flow h5p:generatedefaultconfigsettings.
    defaultConfigSettings:
      # if TRUE, sends usage statistics (#contents, #authors, #librs, etc) to H5P Hub
      # with every content type cache refresh
      send_usage_statistics: false
      # if TRUE, saves ContentResults for logged-in users
      track_user: true
      # if TRUE, saves ContentUserData for logged-in users. This saves data that a frontend user
      # enters during his work with a content, and will restore content state on page reloads.
      save_content_state: true
      # interval in seconds for which the ContentUserData is saved
      save_content_frequency: 10
      # whether or not the H5P hub is enabled.
      hub_is_enabled: true
      # Enables LRS content types.
      enable_lrs_content_types: true
      # content display options
      frame: true
      export: true
      embed: true
      copyright: true
      icon: true
    lrsSettings:
      # The ajax url for sending the xAPI statements to the LRS
      ajax_url: 'https://localhost:8082'
      # enables console-output for all requests to the LRS
      enable_debug_logging: true

    # Setting for the H5PCore->aggregateAssets switch. If set to TRUE, H5P triggers the generation of
    # aggregated assets (CachedAsset) for each content element.
    aggregateAssets: true
    # Set to true to enable the export functionality. This only controls the generation of export files.
    # To make them available for download, you have to enable the "export" config setting above.
    enableExport: true

Neos:

  Neos:
    modules:
      'h5p':
        label: 'H5P Rich Content'
        controller: 'Sandstorm\NeosH5P\Controller\Backend\MainController'
        description: 'Contains modules for managing H5P objects.'
        icon: icon-flash
        submodules:
          content:
            label: 'H5P Content'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ContentController'
            description: 'Create, edit and manage H5P content elements.'
            icon: icon-check-square
            actions:
              new:
                label: 'New H5P Content'
                title: 'Create new H5P content element'
          library:
            label: 'H5P Libraries'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\LibraryController'
            description: 'Manage H5P libraries, get upgraded versions, and update the H5P hub cache.'
            icon: icon-book
          results:
            label: 'H5P User Results'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\ContentResultsController'
            description: 'View and delete user results for H5P content elements.'
            icon: icon-flag-checkered
          administration:
            label: 'H5P Administration'
            controller: 'Sandstorm\NeosH5P\Controller\Backend\AdministrationController'
            description: 'Make administrative settings for H5P.'
            icon: icon-cogs

    fusion:
      autoInclude:
        Sandstorm.NeosH5P: true


  Flow:
    # We need the tag "@variable" as an ignored annotation, because otherwise parsing of the
    # H5PFrameworkInterface causes a reflection error
    reflection:
      ignoredTags:
        'variable': true

    mvc:
      routes:
        'Sandstorm.NeosH5P':
          position: 'start'

    resource:
      storages:
        h5pContentStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\ExtractedContentStorage'
          storageOptions:
            publishingSubfolder: *h5pContentSubfolderName
            resourceGetterMethod: 'getZippedContentFile'
            itemFolderNameMethod: 'getContentId'
        h5pLibraryStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\ExtractedLibraryStorage'
          storageOptions:
            publishingSubfolder: *h5pLibrarySubfolderName
            resourceGetterMethod: 'getZippedLibraryFile'
            itemFolderNameMethod: 'getFolderName'
        h5pCoreStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\H5PPackageFileStorage'
          storageOptions:
            path: '%FLOW_PATH_PACKAGES%Libraries/h5p/'
            library: *h5pCoreSubfolderName
            subfolders:
              - 'fonts'
              - 'images'
              - 'js'
              - 'styles'
        h5pEditorStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\H5PPackageFileStorage'
          storageOptions:
            path: '%FLOW_PATH_PACKAGES%Libraries/h5p/'
            library: *h5pEditorSubfolderName
            subfolders:
              - 'ckeditor'
              - 'images'
              - 'language'
              - 'libs'
              - 'scripts'
              - 'styles'
        h5pEditorTempfilesStorage:
          storage: 'Sandstorm\NeosH5P\Resource\Storage\EditorTempfileStorage'
          storageOptions:
            publishingSubfolder: *h5pEditorTempfilesSubfolderName

      collections:
        h5p-content:
          storage: 'h5pContentStorage'
          target: 'h5pTarget'
        h5p-libraries:
          storage: 'h5pLibraryStorage'
          target: 'h5pTarget'
        h5p-core-files:
          storage: 'h5pCoreStorage'
          target: 'h5pTarget'
        h5p-editor-files:
          storage: 'h5pEditorStorage'
          target: 'h5pTarget'
        h5p-editor-tempfiles:
          storage: 'h5pEditorTempfilesStorage'
          target: 'h5pTarget'

      targets:
        h5pTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemTarget'
          targetOptions:
            path: *h5pPublicFolderPath
            baseUri: *h5pPublicFolderUrl
            subdivideHashPathSegment: false

    # We add a request pattern for our controllers to the Neos Backend provider,
    # so that XHR requests that go directly to these controllers (and not through
    # a ModuleController subrequest) can be authenticated as well
    security:
      authentication:
        providers:
          'Neos.Neos:Backend':
            requestPatterns:
              'Sandstorm.NeosH5P:BackendControllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Sandstorm\NeosH5P\Controller\Backend\.*'
              # TODO: we should not ship this, as we don't really want to persist results for backend users.
              # this is for testing only, and needs to be moved to the integrating package.
              'Sandstorm.NeosH5P:FrontendControllers':
                pattern: 'ControllerObjectName'
                patternOptions:
                  controllerObjectNamePattern: 'Sandstorm\NeosH5P\Controller\Frontend\.*'
